### ISSUE TITLE
Push latest to NPMjs.org

### ISSUE THREAD

**Issue by joshjung** [klaemo/csv-stream#15]
Hey I noticed that the codebase here has the latest version at 2.0.0 but npmjs.org only has version 1.0.0:

https://www.npmjs.com/package/csv-streamify

Any chance you could push the latest to npmjs.org? I'm running into a few issues I would like to fix.

**Comment by klaemo** [comment]
Just published 2.0.0. :)
Thanks for reminding me, I've kind of neglected this module as of late. :(
