### ISSUE TITLE
Quotes inside single-line cells

### ISSUE THREAD

**Issue by rauschma** [klaemo/csv-stream#16]
If there is a quote inside a table cell (e.g. `\tSay "hello"!\t`, if the cell separator is a tab) then csv-stream simply deletes the quote. Google Spreadsheet generates this kind of data if you copy a cell that contains a single line of text and has a quote in it (then the cell itself isn’t quoted and inner quotes aren’t escaped).

IMO, it would be better if such quotes were not removed.

**Comment by klaemo** [comment]
Thanks for bringing this up. I'd argue, though, that csv-stream behaves correctly in this case, because the "standard" [1] says:
> A (double) quote character in a field must be represented by two (double) quote characters.

[1] https://en.wikipedia.org/wiki/Comma-separated_values#Standardization
